import AuthProvider from './(components)/AuthProvider'
import Nav from './(components)/Nav'
import './globals.css'

import AppProvider from './(components)/AppContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppProvider>
        <AuthProvider>
        
          <body className='bg-gray-200'>
            <Nav />
              <div className='m-2'>
                {children}
              </div>
          </body>
          
        </AuthProvider>
        </AppProvider>
    </html>
  )
}
